deployment:
  name: backend
  replicas: 1
  repository: iagouvea/backend
  tag: "7ee2db6"
service:
  name: backend-svc
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  name: backend-ingress
  className: "nginx"
  host: backend.dev.local
