deployment:
  name: backend
  replicas: 1
  repository: iagouvea/backend
  tag: "9e6acc9"


service:
  name: backend-svc
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  name: backend-ingress
  className: "nginx"
  host: backend.dev.local
